### ISSUE TITLE
AttributeError: ownerDocument from the example.py

### ISSUE THREAD

**Issue by SeekPoint** [xmindltd/xmind-sdk-python#31]
C:\ub16_prj>python yk-demo-xmind-sdk.py
Traceback (most recent call last):
  File "yk-demo-xmind-sdk.py", line 19, in <module>
    t1=TopicElement() # create a new element
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\xmind\core\topic.py", line 39, in __init__
    self.addIdAttribute(const.ATTR_ID)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\xmind\core\__init__.py", line 274, in addIdAttribute
    self._node.setAttribute(attr_name, id)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\xml\dom\minidom.py", line 741, in setAttribute
    attr.ownerDocument = self.ownerDocument
AttributeError: ownerDocument

C:\ub16_prj>

**Comment by yuehlin1** [comment]
try this
t1 = TopicElement(ownerWorkbook = w)
instead of 
t1 = TopicElement()

**Comment by SeekPoint** [comment]
it works, @sqohapoe thanks
